#!/bin/bash
while read local_ref local_sha remote_ref remote_sha; do
  if [[ "$remote_ref" == "refs/heads/main" ]]; then
    echo "❌ Push direct sur main interdit ! Crée une branche et ouvre une PR."
    exit 1
  fi
done
exit 0
